#!/usr/bin/escript -c

main(_) ->
    horlogeMatricielle:create_procs(3),
	timer:sleep(10),
    horlogeMatricielle:test_fifo(1, 3, "1"),
	timer:sleep(10),
    horlogeMatricielle:test(1, 2, "2"),
	timer:sleep(10),
    horlogeMatricielle:test(2, 3, "3"),
	timer:sleep(3000),
    horlogeMatricielle:finish().